version: '3.8'

services:
  redis:
    image: bitnami/redis
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - redis_1_data:/bitnami/redis/data
    networks:
      - redis-net
    environment:
      REDIS_PASSWORD: "123"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 135mb --maxmemory-policy allkeys-lfu

  nest-api:
    build: .
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - redis-net


volumes:
  redis_1_data:
  db_data:

networks:
  redis-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16
