version: '3.7'

services:
  redis-node-1:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3
    ports:
      - "6379:6379"  # Mapea el puerto 6379 del contenedor al puerto 6379 del host

  redis-node-2:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3
    ports:
      - "6380:6379"  # Mapea el puerto 6379 del contenedor al puerto 6380 del host

  redis-node-3:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3
    ports:
      - "6381:6379"  # Mapea el puerto 6379 del contenedor al puerto 6381 del host

  redis-cluster-init:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
