version: '3.8'
services:
  nest-api:
    build: .
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    environment:
      POSTGRES_USER: task1
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dataset
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db