version: '3.8'

services:
  redis-master:
    image: bitnami/redis
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis_1_data:/bitnami/redis/data
    networks:
      - redis-net
    environment:
      REDIS_PASSWORD: "123"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 135mb --maxmemory-policy allkeys-lfu

  redis-slave-1:
    image: bitnami/redis
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    volumes:
      - redis_1_data:/bitnami/redis/data
    networks:
      - redis-net
    depends_on:
      - redis-master
    environment:
      REDIS_PASSWORD: "123"
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_PASSWORD: "123"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 135mb --maxmemory-policy allkeys-lfu
  
  redis-slave-2:
    image: bitnami/redis
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    volumes:
      - redis_1_data:/bitnami/redis/data
    networks:
      - redis-net
    depends_on:
      - redis-master
    environment:
      REDIS_PASSWORD: "123"
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_PASSWORD: "123"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 135mb --maxmemory-policy allkeys-lfu

  nest-api:
    build: .
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - redis-net

volumes:
  redis_1_data:
  db_data:

networks:
  redis-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16
