version: '3.8'

services:
  redis-node1:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    ports:
      - "6380:6379"
    networks:
      - app-network

  redis-node2:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    ports:
      - "6381:6379"
    networks:
      - app-network

  redis-node3:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    ports:
      - "6382:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123 
      - POSTGRES_USER=task1
      - POSTGRES_DB=dataset
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - postgres
    environment:
      - REDIS_HOST=redis-node1
      - REDIS_PORT=6379
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
